#!/bin/sh /etc/rc.common

# Created by Tina Cheung, on Feb, 2016 
#
# Connection Manager Daemon (connmgr) Service 
#
# connmgr is a daemon that responsible for monitoring the 
# networking interfaces and based on priorities, select the 
# interface to route the traffic. 
#
# Copyright (c) 2016 - present Afero Inc.   All rights reserved.
#

. /lib/ar71xx.sh

# Note: hubbyservice runs with START=99
#
# We want the script to run after most of the dependents
# and stop before most of deamons. 
START=100
STOP=80

USE_PROCD=1

# Check for diag mode. 
local diag_env

check_diag() {
	diag_ch=`/usr/sbin/fw_printenv diag 2> /dev/null`
	diag_env=`echo $diag_ch | sed 's/diag=1/1/'`
}

check_diag

start_service()
{
    # commands to launch application
    echo start

    # commands to launch application
    if [ ! $diag_env ];
    then
        procd_open_instance
        procd_set_param command /usr/bin/connmgr
        procd_set_param respawn
        [ -e /proc/sys/kernel/core_pattern ] && {
                procd_set_param limits core="unlimited"
                echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
        }
        procd_close_instance
    fi
} 
 
stop() {
    # commands to kill application 
	procd_kill cmservice
}

boot() {
    # commands to run at boot but not at restart

    # continue with the start() section
    start
}

restart() {
    echo restart
    stop
    start
}

shutdown () {
	stop
}
