#!/bin/sh /etc/rc.common

#  Copyright (c) 2016 Afero Inc. All rights reserved.

# We want the script to run
#
START=96
STOP=15

USE_PROCD=1

# Check for diag mode.
local diag_env

check_diag() {
	diag_ch=`/usr/sbin/fw_printenv diag 2> /dev/null`
	diag_env=`echo $diag_ch | sed 's/diag=1/1/'`
}

check_diag

start_service() {
    if [ ! $diag_env ];
    then
		procd_open_instance
		procd_set_param command /lib/wifi_watcher
		procd_set_param respawn
		[ -e /proc/sys/kernel/core_pattern ] && {
			procd_set_param limits core="unlimited"
			echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
		}
		procd_close_instance
    fi
}

stop_service() {
	wifistad_pid=$(pgrep wifistad)

	if [ $wifistad_pid ]; then
		kill $wifistad_pid
	fi
}

stop() {
	procd_kill wifistaservice
}

boot() {
	# commands to run at boot but not at restart

	# continue with the start() section
	start
}

restart() {
	stop "$@"
	start "$@"
}

shutdown() {
	stop
}
